name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pylint mypy

      - name: Black Lint
        uses: psf/black@stable

      - name: Pylint
        run: pylint --fail-under=8 fuzzable/

      # - name: Mypy static typing
      #   run: mypy fuzzable/
  
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest

      #- name: Run tests with pytest
      #  run: pytest

  release:
    runs-on: ubuntu-20.04
    if: "${{ github.event_name == 'push' }}"
    steps:
      - name: Generate releases
        uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: patch
          tag_prefix: "v"
          use_github_release_notes: true

      - name: Get outputs
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
