name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pylint==v3.0.0a3 mypy==v0.902

      - name: Black Lint
        uses: psf/black@stable

      - name: Pylint
        run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')

      - name: Mypy static typing
        run: mypy --strict $(git ls-files '*.py')
  
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest

      - name: Run tests with pytest
        run: pytest 
